<?php

/**
 * ElFinder Includes
 */
$ajaxLibsPath = '//ajax.googleapis.com/ajax/libs';
$publicPath   = $this->basePath() . $this->elPublicPath;


$this->headScript()
    ->appendFile($ajaxLibsPath . '/jquery/1.8.3/jquery.min.js')
    ->appendFile($ajaxLibsPath . '/jqueryui/1.9.2/jquery-ui.min.js')
    ->appendFile($publicPath   . '/js/elfinder.min.js');

$this->headLink()
    ->appendStylesheet($ajaxLibsPath . '/jqueryui/1.9.2/themes/smoothness/jquery-ui.css')
    ->appendStylesheet($publicPath   . '/css/elfinder.min.css')
    ->appendStylesheet($publicPath   . '/css/theme.css');

